steps:
  - label: ':hammer: build for pull-request'
    if: build.branch != "master"
    id: toxic-docker-pr
    command: "tox -p auto"
    plugins:
      - docker#v3.3.0:
          workdir: /repo
          image: "uavcan/toxic:py35-py38-sq"
          propagate-environment: true
    agents:
      queue: 'default'
    timeout_in_minutes: 15
  - label: ':hammer: tox build, test, and release'
    if: build.branch == "master"
    id: toxic-docker-release
    command: "./.buildkite/release.sh"
    artifact_paths: 
      - ".tox/report/tmp/*"
      - ".tox/mypy/tmp/*"
      - ".tox/flake8/tmp/*"
      - ".tox/dist/*.zip"
    plugins:
      - docker#v3.3.0:
          workdir: /repo
          image: "uavcan/toxic:py35-py38-sq"
          propagate-environment: true
          environment:
            - "SONARQUBE_TOKEN"
            - "PYPI_PASSWORD"
    agents:
      queue: 'default'
    timeout_in_minutes: 15
